name: Jira Workflow

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, synchronized, closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
    - name: Update Jira issue
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Create Jira issue
      uses: atlassian/gajira-create@v3
      with:
        project: "YR"
        issuetype: "Task"
        summary: ${{ github.event.issue.title }} # GitHub 이슈의 제목을 사용
        description: ${{ github.event.issue.html_url }} # GitHub 이슈의 URL을 사용
