name: Jira Issue Created

on:
  repository_dispatch:
    types: [jira-issue-created]

jobs:
  create-github-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub Issue
      uses: some-action/github-create-issue@v1
      with:
        issue-title: ${{ github.event.client_payload.issue.title }}
        issue-body: ${{ github.event.client_payload.issue.description }}
        token: ${{ secrets.GIT_TOKEN }}
