name: Jira Workflow

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, synchronized, closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
    - name: Update Jira issue
      uses: atlassian/gajira-login@v2.0.0
      with:
        username: ${{ secrets.JIRA_USERNAME }}
        password: ${{ secrets.JIRA_TOKEN }}
        url: ${{ secrets.JIRA_URL }}
